namespace SGC_PORTFOLIO.Models.Dtos
{
    public class AvailablePdfDto
    {
        /// <summary>
        /// The ID of the PDF (Guid string).
        /// </summary>
        public string PdfId { get; set; }

        /// <summary>
        /// The original file name of the PDF.
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// A short summary generated by GenAI.
        /// </summary>
        public string Summary { get; set; }

        /// <summary>
        /// The list of tags the AI extracted that relate to age restrictions, 
        /// e.g. ["18+", "25+"].
        /// </summary>
        public List<string> AgeTags { get; set; }

        /// <summary>
        /// The list of experience tags (e.g. ["Junior", "Senior"]).
        /// </summary>
        public List<string> ExpTags { get; set; }

        /// <summary>
        /// The list of topic tags extracted by the AI.
        /// </summary>
        public List<string> TopicTags { get; set; }
    }
}
